#:schema node_modules/wrangler/config-schema.json
name = "yukky-sandbox"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = "./dist"

[vars]
BUN_VERSION = "1.1.27"
