name: Playwright Tests
on:
  pull_request:
    branches: [main, develop]
    paths:
      - "**.astro"
      - "**.ts"
      - "**.tsx"
      - "**.mdx"
      - "**.yml"
      - "**.yaml"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          version: 1.1.27
      - name: Install dependencies
        run: bun i --no-save
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
