name: Playwright Tests
on:
  pull_request:
    branches: [main, develop]
    paths:
      - "**.astro"
      - "**.ts"
      - "**.tsx"
      - "**.mdx"
      - "**.json"
      - "**.yml"
      - "**.yaml"
    paths-ignore:
      - ".vscode"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          version: 1.0.30
      - name: Install dependencies
        run: bun i --no-save
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
